<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_DobraValor" Id="{a0d78fc3-7bd3-4ddb-8b8d-f042e4984c9b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DobraValor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_DobraValor">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>