<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{80c62a02-491d-4597-b59c-2fe5867476c4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[prgLab02();
prgLab3A();
prgLab04_06();
prgLab05_07();
prgLab08();
prgLab14B();
prgLab10_11();
prgLab16();

]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="51" Count="8" />
      <LineId Id="28" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>