<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{b8bf13c9-c2a9-42cb-95bd-2f6f16a1c3b2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* Application Engineer: LucasK *)
(* MQTT Sample to TecnoProcess Test *) 
(* Using Mosquitto MQTT Open Source Server *)
(* And MQTT-Explorer to test *)
(* start mosquitto with net start mosquitto *)

]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="6" Count="2" />
      <LineId Id="11" Count="0" />
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>